export type {
  RoadGuidancePosition,
  RoadGuidanceSnapshot,
  SafetyNoticeItem,
  SafetyNoticeSnapshot,
  VariableSpeedLimitItem,
  VariableSpeedLimitSnapshot,
  VmsGuidanceItem,
  VmsGuidancePage,
  VmsGuidanceSnapshot,
} from './model/roadGuidance';
export {
  ROAD_GUIDANCE_MAX_SERIALIZED_BYTES,
  ROAD_GUIDANCE_RESTRICTION_STATE,
  ROAD_GUIDANCE_SPEED_UNIT,
  ROAD_GUIDANCE_TIME_BASIS,
  roadGuidancePositionSchema,
  roadGuidanceSnapshotSchema,
  roadGuidanceSourceTimestampSchema,
  SAFETY_NOTICE_MAX_ITEMS,
  SAFETY_NOTICE_MAX_MESSAGE_LENGTH,
  safetyNoticeDataSchema,
  safetyNoticeItemSchema,
  safetyNoticeSnapshotSchema,
  VARIABLE_SPEED_LIMIT_MAX_ITEMS,
  VMS_GUIDANCE_MAX_ITEMS,
  VMS_GUIDANCE_MAX_LINE_LENGTH,
  VMS_GUIDANCE_MAX_LINES_PER_PAGE,
  VMS_GUIDANCE_MAX_PAGES,
  variableSpeedLimitDataSchema,
  variableSpeedLimitItemSchema,
  variableSpeedLimitSnapshotSchema,
  vmsGuidanceDataSchema,
  vmsGuidanceItemSchema,
  vmsGuidancePageSchema,
  vmsGuidanceSnapshotSchema,
} from './model/roadGuidance';
